# Generated by Django 5.2.7 on 2025-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
