# Generated by Django 5.2.6 on 2025-11-05 05:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('sub_title', models.CharField(default='', max_length=255, verbose_name='زیرعنوان')),
                ('content', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('image', models.ImageField(upload_to='static/sliders/', verbose_name='تصویر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشرشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ویرایش')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ',
            },
        ),
    ]
