"""
Django settings for onlinekala project.

Generated by 'django-admin startproject' using Django 5.2.6.
Modified for Production (IIS + ArvanCloud)
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!v5nhu5wvwf#_!)rn-_v310p11o@o0!99&0-n_-^#%1flc3+$5'

# SECURITY WARNING: don't run with debug turned on in production!
# علی جان، برای پروداکشن حتما باید False باشه
DEBUG = False

# لیست دامنه‌ها و آی‌پی سرور
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'onlinelk.ir',
    'www.onlinelk.ir',
    '87.107.54.96'
]

# Application definition

INSTALLED_APPS = [
    'django_extensions',
    'rest_framework',
    'ckeditor',
    'jazzmin',
    'corsheaders',
    # Apps
    'blog',
    'core',
    'orders',
    'products',
    'web',
    # Default Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # مدیریت فایل‌های استاتیک
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'onlinekala.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'onlinekala.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# فشرده‌سازی فایل‌های استاتیک با Whitenoise (اختیاری ولی مفید)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_header": "مدیریت سایت",
    "site_title": "پنل مدیریت",
    "site_brand": "مدیریت",
    "welcome_sign": "به پنل مدیریت خوش آمدید",
    "custom_css": "css/custom.css"
}

# ==========================================
# Security & HTTPS Settings (ArvanCloud Compatible)
# ==========================================

# 1. تشخیص HTTPS از سمت آروان (بسیار مهم)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 2. ریدایرکت اجباری به HTTPS
SECURE_SSL_REDIRECT = True

# 3. امنیت کوکی‌ها
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# 4. تنظیمات CORS (دسترسی دامنه‌های مجاز)
CORS_ALLOWED_ORIGINS = [
    'https://onlinelk.ir',
    'https://www.onlinelk.ir',
    'https://127.0.0.1',
]

# 5. تنظیمات CSRF Trusted Origins (حیاتی برای لاگین ادمین در Django 4/5)
CSRF_TRUSTED_ORIGINS = [
    'https://onlinelk.ir',
    'https://www.onlinelk.ir',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
]

# 6. HSTS (فعلا خاموش برای جلوگیری از قفل شدن در صورت بروز خطا)
# بعد از 24 ساعت پایداری، مقدار SECONDS را به 3600 یا بیشتر تغییر بده
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

X_FRAME_OPTIONS = 'deny'


# --- Django Extensions runserver_plus SSL config ---
RUNSERVER_PLUS_CERT = os.path.join(BASE_DIR, 'certs', 'cert.pem')
RUNSERVER_PLUS_KEY = os.path.join(BASE_DIR, 'certs', 'key.pem')
