# Generated by Django 5.2.7 on 2025-11-22 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_amount_alter_transaction_amount_and_more'),
        ('products', '0005_product_product_type_alter_product_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اضافه شدن به سبد خرید'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='guest_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کاربرمهمان'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ نهایی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ نهایی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_gateway',
            field=models.CharField(default='ZarinPal', max_length=50, verbose_name='درگاه پرداخت'),
        ),
    ]
