# Generated by Django 5.2.7 on 2025-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_address_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='authority',
            field=models.CharField(default='', max_length=255),
        ),
    ]
