# Generated by Django 5.2.6 on 2025-11-05 05:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='محتوا')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='موجودی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(upload_to='static/sliders/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='یرایش')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
